version: "3.9"

services:
  db:
    image: postgres:14.6
    environment:
      POSTGRES_DB: drip_dev
      POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build:
      context: .
    command: /bin/bash -c "rm -f /tmp/server.pid && bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid"
    environment:
      DATABASE_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./app:/opt/app
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  postgres:
