version: "3.9"

services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: drip_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build:
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      DB_HOST: db
    volumes:
      - ./app:/opt/app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres:
